/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewLobbyRouteImport } from './routes/new-lobby'
import { Route as MyPlayerProfilesRouteImport } from './routes/my-player-profiles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinLobbyLobbyIdRouteImport } from './routes/join-lobby.$lobbyId'
import { Route as HostedLobbyLobbyIdRouteImport } from './routes/hosted-lobby.$lobbyId'
import { Route as HostedGamesTableIdRouteImport } from './routes/hosted-games.$tableId'
import { Route as GamesTableIdRouteImport } from './routes/games.$tableId'
import { Route as JoinLobbyLobbyIdIndexRouteImport } from './routes/join-lobby.$lobbyId/index'
import { Route as HostedLobbyLobbyIdIndexRouteImport } from './routes/hosted-lobby.$lobbyId/index'
import { Route as GamesTableIdIndexRouteImport } from './routes/games.$tableId/index'
import { Route as JoinLobbyLobbyIdP2pDetailsRouteImport } from './routes/join-lobby.$lobbyId/p2p-details'
import { Route as HostedLobbyLobbyIdPlayerRouteImport } from './routes/hosted-lobby.$lobbyId/player'
import { Route as HostedLobbyLobbyIdP2pDetailsRouteImport } from './routes/hosted-lobby.$lobbyId/p2p-details'
import { Route as GamesTableIdObserveRouteImport } from './routes/games.$tableId/observe'

const NewLobbyRoute = NewLobbyRouteImport.update({
  id: '/new-lobby',
  path: '/new-lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPlayerProfilesRoute = MyPlayerProfilesRouteImport.update({
  id: '/my-player-profiles',
  path: '/my-player-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinLobbyLobbyIdRoute = JoinLobbyLobbyIdRouteImport.update({
  id: '/join-lobby/$lobbyId',
  path: '/join-lobby/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedLobbyLobbyIdRoute = HostedLobbyLobbyIdRouteImport.update({
  id: '/hosted-lobby/$lobbyId',
  path: '/hosted-lobby/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostedGamesTableIdRoute = HostedGamesTableIdRouteImport.update({
  id: '/hosted-games/$tableId',
  path: '/hosted-games/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTableIdRoute = GamesTableIdRouteImport.update({
  id: '/games/$tableId',
  path: '/games/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinLobbyLobbyIdIndexRoute = JoinLobbyLobbyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JoinLobbyLobbyIdRoute,
} as any)
const HostedLobbyLobbyIdIndexRoute = HostedLobbyLobbyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostedLobbyLobbyIdRoute,
} as any)
const GamesTableIdIndexRoute = GamesTableIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesTableIdRoute,
} as any)
const JoinLobbyLobbyIdP2pDetailsRoute =
  JoinLobbyLobbyIdP2pDetailsRouteImport.update({
    id: '/p2p-details',
    path: '/p2p-details',
    getParentRoute: () => JoinLobbyLobbyIdRoute,
  } as any)
const HostedLobbyLobbyIdPlayerRoute =
  HostedLobbyLobbyIdPlayerRouteImport.update({
    id: '/player',
    path: '/player',
    getParentRoute: () => HostedLobbyLobbyIdRoute,
  } as any)
const HostedLobbyLobbyIdP2pDetailsRoute =
  HostedLobbyLobbyIdP2pDetailsRouteImport.update({
    id: '/p2p-details',
    path: '/p2p-details',
    getParentRoute: () => HostedLobbyLobbyIdRoute,
  } as any)
const GamesTableIdObserveRoute = GamesTableIdObserveRouteImport.update({
  id: '/observe',
  path: '/observe',
  getParentRoute: () => GamesTableIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-player-profiles': typeof MyPlayerProfilesRoute
  '/new-lobby': typeof NewLobbyRoute
  '/games/$tableId': typeof GamesTableIdRouteWithChildren
  '/hosted-games/$tableId': typeof HostedGamesTableIdRoute
  '/hosted-lobby/$lobbyId': typeof HostedLobbyLobbyIdRouteWithChildren
  '/join-lobby/$lobbyId': typeof JoinLobbyLobbyIdRouteWithChildren
  '/games/$tableId/observe': typeof GamesTableIdObserveRoute
  '/hosted-lobby/$lobbyId/p2p-details': typeof HostedLobbyLobbyIdP2pDetailsRoute
  '/hosted-lobby/$lobbyId/player': typeof HostedLobbyLobbyIdPlayerRoute
  '/join-lobby/$lobbyId/p2p-details': typeof JoinLobbyLobbyIdP2pDetailsRoute
  '/games/$tableId/': typeof GamesTableIdIndexRoute
  '/hosted-lobby/$lobbyId/': typeof HostedLobbyLobbyIdIndexRoute
  '/join-lobby/$lobbyId/': typeof JoinLobbyLobbyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-player-profiles': typeof MyPlayerProfilesRoute
  '/new-lobby': typeof NewLobbyRoute
  '/hosted-games/$tableId': typeof HostedGamesTableIdRoute
  '/games/$tableId/observe': typeof GamesTableIdObserveRoute
  '/hosted-lobby/$lobbyId/p2p-details': typeof HostedLobbyLobbyIdP2pDetailsRoute
  '/hosted-lobby/$lobbyId/player': typeof HostedLobbyLobbyIdPlayerRoute
  '/join-lobby/$lobbyId/p2p-details': typeof JoinLobbyLobbyIdP2pDetailsRoute
  '/games/$tableId': typeof GamesTableIdIndexRoute
  '/hosted-lobby/$lobbyId': typeof HostedLobbyLobbyIdIndexRoute
  '/join-lobby/$lobbyId': typeof JoinLobbyLobbyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-player-profiles': typeof MyPlayerProfilesRoute
  '/new-lobby': typeof NewLobbyRoute
  '/games/$tableId': typeof GamesTableIdRouteWithChildren
  '/hosted-games/$tableId': typeof HostedGamesTableIdRoute
  '/hosted-lobby/$lobbyId': typeof HostedLobbyLobbyIdRouteWithChildren
  '/join-lobby/$lobbyId': typeof JoinLobbyLobbyIdRouteWithChildren
  '/games/$tableId/observe': typeof GamesTableIdObserveRoute
  '/hosted-lobby/$lobbyId/p2p-details': typeof HostedLobbyLobbyIdP2pDetailsRoute
  '/hosted-lobby/$lobbyId/player': typeof HostedLobbyLobbyIdPlayerRoute
  '/join-lobby/$lobbyId/p2p-details': typeof JoinLobbyLobbyIdP2pDetailsRoute
  '/games/$tableId/': typeof GamesTableIdIndexRoute
  '/hosted-lobby/$lobbyId/': typeof HostedLobbyLobbyIdIndexRoute
  '/join-lobby/$lobbyId/': typeof JoinLobbyLobbyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-player-profiles'
    | '/new-lobby'
    | '/games/$tableId'
    | '/hosted-games/$tableId'
    | '/hosted-lobby/$lobbyId'
    | '/join-lobby/$lobbyId'
    | '/games/$tableId/observe'
    | '/hosted-lobby/$lobbyId/p2p-details'
    | '/hosted-lobby/$lobbyId/player'
    | '/join-lobby/$lobbyId/p2p-details'
    | '/games/$tableId/'
    | '/hosted-lobby/$lobbyId/'
    | '/join-lobby/$lobbyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-player-profiles'
    | '/new-lobby'
    | '/hosted-games/$tableId'
    | '/games/$tableId/observe'
    | '/hosted-lobby/$lobbyId/p2p-details'
    | '/hosted-lobby/$lobbyId/player'
    | '/join-lobby/$lobbyId/p2p-details'
    | '/games/$tableId'
    | '/hosted-lobby/$lobbyId'
    | '/join-lobby/$lobbyId'
  id:
    | '__root__'
    | '/'
    | '/my-player-profiles'
    | '/new-lobby'
    | '/games/$tableId'
    | '/hosted-games/$tableId'
    | '/hosted-lobby/$lobbyId'
    | '/join-lobby/$lobbyId'
    | '/games/$tableId/observe'
    | '/hosted-lobby/$lobbyId/p2p-details'
    | '/hosted-lobby/$lobbyId/player'
    | '/join-lobby/$lobbyId/p2p-details'
    | '/games/$tableId/'
    | '/hosted-lobby/$lobbyId/'
    | '/join-lobby/$lobbyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyPlayerProfilesRoute: typeof MyPlayerProfilesRoute
  NewLobbyRoute: typeof NewLobbyRoute
  GamesTableIdRoute: typeof GamesTableIdRouteWithChildren
  HostedGamesTableIdRoute: typeof HostedGamesTableIdRoute
  HostedLobbyLobbyIdRoute: typeof HostedLobbyLobbyIdRouteWithChildren
  JoinLobbyLobbyIdRoute: typeof JoinLobbyLobbyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-lobby': {
      id: '/new-lobby'
      path: '/new-lobby'
      fullPath: '/new-lobby'
      preLoaderRoute: typeof NewLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-player-profiles': {
      id: '/my-player-profiles'
      path: '/my-player-profiles'
      fullPath: '/my-player-profiles'
      preLoaderRoute: typeof MyPlayerProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-lobby/$lobbyId': {
      id: '/join-lobby/$lobbyId'
      path: '/join-lobby/$lobbyId'
      fullPath: '/join-lobby/$lobbyId'
      preLoaderRoute: typeof JoinLobbyLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted-lobby/$lobbyId': {
      id: '/hosted-lobby/$lobbyId'
      path: '/hosted-lobby/$lobbyId'
      fullPath: '/hosted-lobby/$lobbyId'
      preLoaderRoute: typeof HostedLobbyLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosted-games/$tableId': {
      id: '/hosted-games/$tableId'
      path: '/hosted-games/$tableId'
      fullPath: '/hosted-games/$tableId'
      preLoaderRoute: typeof HostedGamesTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$tableId': {
      id: '/games/$tableId'
      path: '/games/$tableId'
      fullPath: '/games/$tableId'
      preLoaderRoute: typeof GamesTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-lobby/$lobbyId/': {
      id: '/join-lobby/$lobbyId/'
      path: '/'
      fullPath: '/join-lobby/$lobbyId/'
      preLoaderRoute: typeof JoinLobbyLobbyIdIndexRouteImport
      parentRoute: typeof JoinLobbyLobbyIdRoute
    }
    '/hosted-lobby/$lobbyId/': {
      id: '/hosted-lobby/$lobbyId/'
      path: '/'
      fullPath: '/hosted-lobby/$lobbyId/'
      preLoaderRoute: typeof HostedLobbyLobbyIdIndexRouteImport
      parentRoute: typeof HostedLobbyLobbyIdRoute
    }
    '/games/$tableId/': {
      id: '/games/$tableId/'
      path: '/'
      fullPath: '/games/$tableId/'
      preLoaderRoute: typeof GamesTableIdIndexRouteImport
      parentRoute: typeof GamesTableIdRoute
    }
    '/join-lobby/$lobbyId/p2p-details': {
      id: '/join-lobby/$lobbyId/p2p-details'
      path: '/p2p-details'
      fullPath: '/join-lobby/$lobbyId/p2p-details'
      preLoaderRoute: typeof JoinLobbyLobbyIdP2pDetailsRouteImport
      parentRoute: typeof JoinLobbyLobbyIdRoute
    }
    '/hosted-lobby/$lobbyId/player': {
      id: '/hosted-lobby/$lobbyId/player'
      path: '/player'
      fullPath: '/hosted-lobby/$lobbyId/player'
      preLoaderRoute: typeof HostedLobbyLobbyIdPlayerRouteImport
      parentRoute: typeof HostedLobbyLobbyIdRoute
    }
    '/hosted-lobby/$lobbyId/p2p-details': {
      id: '/hosted-lobby/$lobbyId/p2p-details'
      path: '/p2p-details'
      fullPath: '/hosted-lobby/$lobbyId/p2p-details'
      preLoaderRoute: typeof HostedLobbyLobbyIdP2pDetailsRouteImport
      parentRoute: typeof HostedLobbyLobbyIdRoute
    }
    '/games/$tableId/observe': {
      id: '/games/$tableId/observe'
      path: '/observe'
      fullPath: '/games/$tableId/observe'
      preLoaderRoute: typeof GamesTableIdObserveRouteImport
      parentRoute: typeof GamesTableIdRoute
    }
  }
}

interface GamesTableIdRouteChildren {
  GamesTableIdObserveRoute: typeof GamesTableIdObserveRoute
  GamesTableIdIndexRoute: typeof GamesTableIdIndexRoute
}

const GamesTableIdRouteChildren: GamesTableIdRouteChildren = {
  GamesTableIdObserveRoute: GamesTableIdObserveRoute,
  GamesTableIdIndexRoute: GamesTableIdIndexRoute,
}

const GamesTableIdRouteWithChildren = GamesTableIdRoute._addFileChildren(
  GamesTableIdRouteChildren,
)

interface HostedLobbyLobbyIdRouteChildren {
  HostedLobbyLobbyIdP2pDetailsRoute: typeof HostedLobbyLobbyIdP2pDetailsRoute
  HostedLobbyLobbyIdPlayerRoute: typeof HostedLobbyLobbyIdPlayerRoute
  HostedLobbyLobbyIdIndexRoute: typeof HostedLobbyLobbyIdIndexRoute
}

const HostedLobbyLobbyIdRouteChildren: HostedLobbyLobbyIdRouteChildren = {
  HostedLobbyLobbyIdP2pDetailsRoute: HostedLobbyLobbyIdP2pDetailsRoute,
  HostedLobbyLobbyIdPlayerRoute: HostedLobbyLobbyIdPlayerRoute,
  HostedLobbyLobbyIdIndexRoute: HostedLobbyLobbyIdIndexRoute,
}

const HostedLobbyLobbyIdRouteWithChildren =
  HostedLobbyLobbyIdRoute._addFileChildren(HostedLobbyLobbyIdRouteChildren)

interface JoinLobbyLobbyIdRouteChildren {
  JoinLobbyLobbyIdP2pDetailsRoute: typeof JoinLobbyLobbyIdP2pDetailsRoute
  JoinLobbyLobbyIdIndexRoute: typeof JoinLobbyLobbyIdIndexRoute
}

const JoinLobbyLobbyIdRouteChildren: JoinLobbyLobbyIdRouteChildren = {
  JoinLobbyLobbyIdP2pDetailsRoute: JoinLobbyLobbyIdP2pDetailsRoute,
  JoinLobbyLobbyIdIndexRoute: JoinLobbyLobbyIdIndexRoute,
}

const JoinLobbyLobbyIdRouteWithChildren =
  JoinLobbyLobbyIdRoute._addFileChildren(JoinLobbyLobbyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyPlayerProfilesRoute: MyPlayerProfilesRoute,
  NewLobbyRoute: NewLobbyRoute,
  GamesTableIdRoute: GamesTableIdRouteWithChildren,
  HostedGamesTableIdRoute: HostedGamesTableIdRoute,
  HostedLobbyLobbyIdRoute: HostedLobbyLobbyIdRouteWithChildren,
  JoinLobbyLobbyIdRoute: JoinLobbyLobbyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
